//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.Services.ClientTest.MoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleBookTraceInformation", Namespace="http://schemas.datacontract.org/2004/07/More.Engine.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(More.Services.ClientTest.MoreService.RuleBookTraceInformation[]))]
    public partial class RuleBookTraceInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private More.Services.ClientTest.MoreService.RuleBookTraceInformation[] _childrenField;
        
        private string ContextIdk__BackingFieldField;
        
        private string Descriptionk__BackingFieldField;
        
        private string Expressionk__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private string LoopContextk__BackingFieldField;
        
        private string RuleIdk__BackingFieldField;
        
        private object Valuek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public More.Services.ClientTest.MoreService.RuleBookTraceInformation[] _children {
            get {
                return this._childrenField;
            }
            set {
                if ((object.ReferenceEquals(this._childrenField, value) != true)) {
                    this._childrenField = value;
                    this.RaisePropertyChanged("_children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ContextId>k__BackingField", IsRequired=true)]
        public string ContextIdk__BackingField {
            get {
                return this.ContextIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextIdk__BackingFieldField, value) != true)) {
                    this.ContextIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ContextIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Description>k__BackingField", IsRequired=true)]
        public string Descriptionk__BackingField {
            get {
                return this.Descriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Descriptionk__BackingFieldField, value) != true)) {
                    this.Descriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Descriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Expression>k__BackingField", IsRequired=true)]
        public string Expressionk__BackingField {
            get {
                return this.Expressionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Expressionk__BackingFieldField, value) != true)) {
                    this.Expressionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Expressionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LoopContext>k__BackingField", IsRequired=true)]
        public string LoopContextk__BackingField {
            get {
                return this.LoopContextk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LoopContextk__BackingFieldField, value) != true)) {
                    this.LoopContextk__BackingFieldField = value;
                    this.RaisePropertyChanged("LoopContextk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RuleId>k__BackingField", IsRequired=true)]
        public string RuleIdk__BackingField {
            get {
                return this.RuleIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleIdk__BackingFieldField, value) != true)) {
                    this.RuleIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("RuleIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Value>k__BackingField", IsRequired=true)]
        public object Valuek__BackingField {
            get {
                return this.Valuek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Valuek__BackingFieldField, value) != true)) {
                    this.Valuek__BackingFieldField = value;
                    this.RaisePropertyChanged("Valuek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoreService.IMoreService")]
    public interface IMoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoreService/Execute", ReplyAction="http://tempuri.org/IMoreService/ExecuteResponse")]
        More.Services.ClientTest.MoreService.RuleBookTraceInformation[] Execute(System.DateTime effectiveDate, string ruleBook, System.Collections.Generic.Dictionary<string, object> inputs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoreServiceChannel : More.Services.ClientTest.MoreService.IMoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoreServiceClient : System.ServiceModel.ClientBase<More.Services.ClientTest.MoreService.IMoreService>, More.Services.ClientTest.MoreService.IMoreService {
        
        public MoreServiceClient() {
        }
        
        public MoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public More.Services.ClientTest.MoreService.RuleBookTraceInformation[] Execute(System.DateTime effectiveDate, string ruleBook, System.Collections.Generic.Dictionary<string, object> inputs) {
            return base.Channel.Execute(effectiveDate, ruleBook, inputs);
        }
    }
}
